name: Deploy to Play Store

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/*.md'
      - '*.txt'

jobs:
  deploy:
    name: Build & Deploy to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any' # Sử dụng bản stable mới nhất phù hợp với SDK của bạn
          channel: 'stable'
          cache: true

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: android

      - name: Cache pubspec dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.config/flutter
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        env:
          B64_DATA: ${{ secrets.KEYSTORE_BASE64 }}
        run: python3 -c "import base64, os; open('android/app/keystore.jks', 'wb').write(base64.b64decode(os.environ['B64_DATA']))"

      - name: Create key.properties
        env:
          STORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASS: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          python3 -c "import os; f=open('android/key.properties', 'w'); f.write('storePassword=' + os.environ['STORE_PASS'] + '\nkeyPassword=' + os.environ['KEY_PASS'] + '\nkeyAlias=' + os.environ['ALIAS'] + '\nstoreFile=keystore.jks\n'); f.close()"

      - name: Decode Google Play Credentials
        env:
          B64_DATA: ${{ secrets.PLAY_STORE_CREDENTIALS_BASE64 }}
        run: python3 -c "import base64, os; open('android/play-store-credentials.json', 'wb').write(base64.b64decode(os.environ['B64_DATA']))"

      - name: Generate env.json
        env:
          B64_DATA: ${{ secrets.ENV_JSON_BASE64 }}
        run: python3 -c "import base64, os; open('env.json', 'wb').write(base64.b64decode(os.environ['B64_DATA']))"

      - name: Build App Bundle
        run: flutter build appbundle --release --build-number=$(( ${{ github.run_number }} + 20 ))

      - name: Execute Fastlane Deploy
        working-directory: android
        run: bundle exec fastlane deploy
