name: Deploy to Play Store

on:
  push:
    branches:
      - master
      - main
      - refactor/new-core-clean-architecture

jobs:
  deploy:
    name: Build & Deploy to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any' # Sử dụng bản stable mới nhất phù hợp với SDK của bạn
          channel: 'stable'
          cache: true

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: android

      - name: Cache pubspec dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.config/flutter
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Decode Google Play Credentials
        run: |
          echo "${{ secrets.PLAY_STORE_CREDENTIALS_BASE64 }}" | base64 --decode > android/play-store-credentials.json

      - name: Generate env.json
        run: |
          echo "${{ secrets.ENV_JSON_BASE64 }}" | base64 --decode > env.json

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Execute Fastlane Deploy
        working-directory: android
        run: bundle exec fastlane deploy
